In [1]:
import torch

In [ ]:
# Scalar

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


In [4]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [8]:
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

In [ ]:
# Vector

In [3]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [4]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [5]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [6]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [7]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [8]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [9]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [10]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [11]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [12]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [14]:
torch.dot(vector1, vector2)

tensor(32.)

In [15]:
# Matrix
# 2개 이상의 벡터 값을 통합해 구성된 값
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [17]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [18]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [19]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [21]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [22]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [23]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [24]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [25]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [26]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])