In [1]:
import torch

In [ ]:
# Scalar

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


In [4]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [8]:
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

In [ ]:
# Vector

In [3]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [4]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [5]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [6]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [7]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [8]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [9]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [10]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [11]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [12]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [14]:
torch.dot(vector1, vector2)

tensor(32.)

In [15]:
# Matrix
# 2개 이상의 벡터 값을 통합해 구성된 값
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [17]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [18]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [19]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [21]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [22]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [23]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [24]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [25]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [26]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

In [ ]:
# tensor

In [2]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [3]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [4]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [5]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [7]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [8]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [9]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [10]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [12]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [13]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [14]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

## 여기서부터 실행

In [2]:
import torch

In [5]:
# 파이토치를 이용해 코드를 작성할 때 Back Propargation을 이용해 파라미터를 업데이트 하는 방법은
# Autograd 방식으로 쉽게 구현할 수 있음
# 간단한 딥러닝 모델 설계와 방정식 내 파라미터 업데이트

In [3]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [4]:
BATCH_SIZE = 64 # 딥러닝 모델에서 파라미터를 업데이트할 때 계산되는 데이터의 개수
INPUT_SIZE = 1000 # 딥러닝 모델 Input 크기이자 입력층의 노드 수
HIDDEN_SIZE = 100 # 은닉층의 노드 수
OUTPUT_SIZE = 10 # 최종 출력 값 벡터 크기

In [5]:
x = torch.randn(BATCH_SIZE,
               INPUT_SIZE,
               device = DEVICE,
               dtype = torch.float,
               requires_grad = False)
y = torch.randn(BATCH_SIZE,
               OUTPUT_SIZE,
               device = DEVICE,
               dtype = torch.float,
               requires_grad = False)
w1 = torch.randn(INPUT_SIZE,
                HIDDEN_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE,
                OUTPUT_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = True)

In [6]:
learning_rate = 1e-6 # (1)
for t in range(1, 501): # (2)
    y_pred = x.mm(w1).clamp(min = 0).mm(w2) # (3)
    
    loss = (y_pred - y).pow(2).sum() # (4)
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item()) # (5)
    loss.backward() # (6)
    
    with torch.no_grad( ): # (7)
        w1 -= learning_rate * w1.grad # (8)
        w2 -= learning_rate * w2.grad # (9)
        
        w1.grad.zero_() # (10)
        w2.grad.zero_() # (11)

Iteration:  100 	 Loss:  257.18829345703125
Iteration:  200 	 Loss:  0.38274702429771423
Iteration:  300 	 Loss:  0.0011923240963369608
Iteration:  400 	 Loss:  5.794420576421544e-05
Iteration:  500 	 Loss:  1.6187010260182433e-05
