##### This is practicing for numpy 101 examples.
##### 개인적으로 중요하다고 느낀 건 'useful' 이라고 tagging
##### 어려운건 'hard'

#### https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [2]:
# 1. Import numpy as np and see the version
print(np.__version__)

1.20.1


In [15]:
# 2. How to create a 1D array?
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 3. How to create a boolean array?
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
# Alternate method:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [2]:
# 4. How to extract items that satisfy a given condition from 1D array?

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [3]:
# 5. How to replace items that satisfy a condition with another value in numpy array?

arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
# 6. How to replace items that satisfy a condition without affecting the original array?

# 5번이랑 차이점은 새로운 array를 추가로 생성한다는 것

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [5]:
# 7. How to reshape an array?
# Convert a 1D array to a 2D array with 2 rows

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
# 8. How to stack two arrays vertically? (useful)
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

In [8]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# Answer
# Method 1
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# Method 2
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# Method 3
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# 9. How to stack two arrays horizontally? (useful)
# Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

In [14]:
# Answers
# Method 1
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
# Method 2
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
# Method 3
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
# 10. How to generate custom sequences in numpy without hardcoding? (useful)

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [18]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])